name: Continuous Deployment

on:
  release:
    types: [published, edited]

jobs:
  deploy:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "onlineweb-frontend"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_e04e52940ded45e3afdf32dfab711104 }}
          package: .
